### ISSUE TITLE
Konflikt mit menatwork/contao-multicolumnwizard

### ISSUE THREAD

**Issue by swinde** [MetaModels/bundle_all#7]
Beim Versuch dieses Bundel mit Contao Manager zu installieren, kommt es zu einem Konflikt und die Installation wird abgebrochen wenn menatwork/contao-multicolumnwizard (Version 3.3) schon installiert ist. 
Das benötigte Modul menatwork/contao-multicolumnwizard-bundel wird nicht installiert.

**Comment by richardhj** [comment]
check https://github.com/terminal42/contao-changelanguage/issues/158#issuecomment-469316068

**Comment by swinde** [comment]
Hallo!
Die Lösung funktioniert wenn man uneingeschränkten Zugriff, über die Konsole, auf Composer hat. Lokal habe ich es hin bekommen. Auf meinem Virtuellen Server wegen Memoryproblemen nicht!
Mit Contao Manager ist die Installation nicht möglich!

**Comment by richardhj** [comment]
wenn du es lokal hinbekommen hast, dann bitte die `composer.json` auf den Server hochladen und dann per Contao-Manager unter "Maintenance" > "Run Installer" installieren.

**Comment by discordier** [comment]
We could(!) add a conflict in 2.1.x but this will not solve the problem but only change the error message of composer so that no matching version of the mcw has been found which would be more confusing IMO.

As to another reason why we should not add it, see the comment of @richardhj in the above linked issue.
